# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('brewery', models.CharField(max_length=512)),
                ('country', models.CharField(max_length=512)),
                ('style', models.CharField(max_length=512)),
                ('abv', models.FloatField()),
                ('ibu', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('purchase_url', models.URLField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('participants', models.IntegerField()),
                ('volume_per_participant', models.FloatField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feer.Beer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='order date')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beers', models.ManyToManyField(through='feer.OrderItem', to='feer.Beer')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feer.OrderList'),
        ),
    ]
