# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0002_orderlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_date',
            field=models.DateField(verbose_name='order date'),
        ),
    ]
