# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0005_orderitem_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_list',
            new_name='order',
        ),
    ]
