# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0006_auto_20160116_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='drink_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='drink date'),
            preserve_default=False,
        ),
    ]
