# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feer', '0007_orderitem_drink_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='participants',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
