# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0009_auto_20160120_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='ibu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
