# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0012_auto_20160206_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='index',
            field=models.IntegerField(),
        ),
    ]
