# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0016_remove_orderitem_volume_per_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cost',
        ),
    ]
