# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0017_auto_20160402_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 2, 13, 2, 31, 578232, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 2, 13, 2, 42, 186093, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 2, 13, 3, 14, 39186, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 2, 13, 3, 16, 30779, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 2, 13, 3, 17, 232609, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 2, 13, 3, 18, 336149, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 2, 13, 3, 19, 415807, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 2, 13, 3, 20, 447692, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
