# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0018_auto_20160402_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remainding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
