# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0019_order_remainding_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updatedable',
            field=models.BooleanField(default=True),
        ),
    ]
