# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0020_order_updatedable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updatedable',
            new_name='updatable',
        ),
    ]
