# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feer', '0021_auto_20160501_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_for_free_shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
